### ISSUE TITLE
Screen just goes black

### ISSUE THREAD

**Issue by MagnusStrom** [lucafabbian/electron-iso-packager#1]
After producing and booting, i get to the the tinycore linux opening, I press enter and it goes through some stuff and the last thing I see is just "Loading extentions" and then the screen goes completely black.

**Comment by lucafabbian** [comment]
Looks like I forgot to list electron-packager in the dependencies.
You can fix it by installing electron-packager manually. Just type `sudo npm install -g electron-packager`
I'll update the docs soon

**Comment by MagnusStrom** [comment]
![image](https://user-images.githubusercontent.com/80227480/126242516-6ca85eec-a006-4688-940c-62ed556aca8b.png)
@lucafabbian Why is it doing this?

**Comment by lucafabbian** [comment]
It looks like it's not loading the electron app. It could be possible the app crashed somewhere in the process. I'm unable to reproduce.
May I ask you what app are you trying to build with this module? Is it a public github project?

**Comment by MagnusStrom** [comment]
@lucafabbian https://github.com/MagnusStrom/Arobic

I'm trying to make an Actual operating system. is this the project for me? could i maybe just force fullscreen my program?

**Comment by lucafabbian** [comment]
Fixed! I managed to got your app work. It looks like newer version of electron uses a library called "libxkbcommon" which must be added to the iso. I'm going to pull tomorrow, after checking that everything is fine.

After reading your code, I think this project is definitely the one you're looking for. As you said, electron-iso-packager doesn't force fullscreen by default. It should be possibile to force fullscreen using the autostart file, but I suggest to trigger fullscreen internally as you would for every normal electron app (or just remove window borders).

**Comment by MagnusStrom** [comment]
So what do i do? I only have a mac, so I'm using github actions to compile. Can i do it myself right now? I have a fork that Im using for the actions

**Comment by MagnusStrom** [comment]
@lucafabbian can i add it rn?

**Comment by lucafabbian** [comment]
Since I'm here, I'd like to update the tinycore version too and to automate the updating process.
just give a couple of hours and everything will be ready :)

**Comment by MagnusStrom** [comment]
Sorry, I did not realize your timezone. Thank you for the help!

**Comment by lucafabbian** [comment]
Done :)
Just update electron-iso-packager to version 1.0.1 through npm.
I tested it on my machine, and Arobic was working perfectly.

**Comment by MagnusStrom** [comment]
Thank you! Can I also control linux functions using electron?

**Comment by MagnusStrom** [comment]
Fixed!
